spring :
  application :
    name : config-service
  cloud:
    discovery:
      enabled : true
    server:
      git:
        default-label : main
        uri : https://github.com/Alae7/ConfigHotel.git

server:
  port : 9999

eureka:
  client:
    service-url:
      defaultZone : ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include : *
